default_language: en_US

admins:  # Administrators who cannot be banned (all in lowercase)
  - taskov1ch
  - tester

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite

  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema

  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

# Enter a list of commands that will be executed on behalf of the console.
# If anything, this is a reward for the players who actually banned the violator and presented evidence.
rewards:
  - kick {%player} LOL :)

time_limit: 21600  # Time to provide evidence in seconds (if there is no evidence, then ban)